### PR TITLE
Fix root link to top of page

### PR DESCRIPTION
**Pull request by spenserblack**
A "Jump to start" link is much more helpful when you don't have to scroll to the start to click it :rofl:

This PR also fixes a small typo

### CODE REVIEW

**Comment by Floffah** [comment]
Hi, are you talking about in the docs page?

**Comment by Floffah** [comment]
This isn't actually made by me. This was generated by one of my other libraries called better-nearley-railroad which you can find here: https://github.com/floffah/better-nearley-railroad

**Comment by spenserblack** [comment]
>Hi, are you talking about in the docs page?

Yeah, that's right. Found this project recently and was just reading the docs recently when I thought I'd make this PR to fix it.

**Comment by spenserblack** [comment]
>This was generated

Oh, that makes much more sense :laughing: 
I was wondering why you were referencing templates in this project. Do you want me to make a PR there?

Closing this PR since the root of the issue is in another project.

**Comment by Floffah** [comment]
Yes, it should be easy as this uses the default template from that repository. Thank you :)

**Comment by Floffah** [comment]
I will publish a new release with these changes for that tool after

**Pull request closed without merging**
